### ISSUE TITLE
Messung beenden klappt nicht immer

### ISSUE THREAD

**Issue by Rastopapola** [sebastianpauli/netgis-client#34]
# Status quo

(Sehr wilder Bug imho)

Ich hatte erwartet, dass der Doppelklick eine Messung beendet. Allerdings tat er das nicht. Nach vielen wilden Doppelklicken endete die Messung dann schließlich doch irgendwann. Weil ich dachte, dass ggf. Fehler in der Firefox Konsole auszulesen wären, öffnete ich diese und plötzlich "gehorcht" der Doppelklick, wenn die Konsole geöffnet ist (siehe GIF). Ich vermute, dass es einen Zusammenhang zwischen der Viewportgröße (Viewport wird durch geöffnete Konsole kleiner) und dem Verhalten des Bugs geben muss - auch, wenn ich ihn mir nicht wirklich erklären kann.

  
![Peek 2024-11-02 12-26](https://github.com/user-attachments/assets/2ceffb0e-df71-4986-b6fc-267b5a2e4348)

**Comment by Rastopapola** [comment]
Habe gerade bemerkt, dass es sich um ein generelles Problem beim Doppelklicken handelt. Getestet auf Firefox 132.0 (64-Bit) und Google Chrom Version 129.0.6668.100 (Offizieller Build) (64-Bit).

**Comment by Rastopapola** [comment]
Weitere Erkenntnis: Mit der rechten Maustaste lässt sich ebenfalls ein Vertex setzen und noch dazu: Ein Doppelklick mit Rechts beendet die Eingabe zuverlässig, so wie es früher der linke Doppelklick getan hat. Vielleicht hilft das bei der weiteren Buganalyse?

**Comment by sebastianpauli** [comment]
A tricky issue, but should be fixed (or at least mitigated) in latest [commit](https://github.com/sebastianpauli/netgis-client/commit/bb4bc31d8a915176848856014e29297fd585f2cb).

The problem seems to be connected to OpenLayers map click detection, which tries to seperate pointer inputs like clicks (and therefore double clicks) from panning movements.

A new **map config parameter "move_tolerance"** has been added, to allow the fine tuning of this click detection. The higher this tolerance (in viewport pixels), the easier it is to click or double click but map panning will begin only after the move tolerance has been exceded.

Example:

```
"map":
{
	// ...
	"move_tolerance": 10
}
```

Also the default move tolerance has been set to 7 to allow easier click detection by default.

Additionally since the last larger update it is also possible (but not yet documented) to finish line/polygon/measure drawing using the **Enter/Return** key or to cancel using the **Escape** key.

**Comment by Rastopapola** [comment]
Sadly, the new parameter does not seem to do anything for me (or at least, I do not fully understand what exactly I'm supposed to expect). 
The new situation is like this:

* Enter/Return works for marking the end of measuring (but is not intuitive)
* Double left click still does not properly end the measuring (sometimes it does, sometimes not)
* Right click (now?) has two different behaviour:
    *  If right clicked on the last placed (left clicked vertex the measuring ends properly with all set vertices
    * If right clicked somewhere else (not on the last placed vertex) the whole measuring is being reset and disappears

The expected behaviour would be (at least for me):
* Left click places vertex
* Double left click places vertex and ends measuring
* (optionally) Right click drops last places vertex (like LIFO 'undo')

**Comment by Rastopapola** [comment]
# Update

Looks like a general problem with a double-click. Just encountered the same odd behaviour on the cut tool, where one needs to draw the cut-shape on the to-be-cut-polygon. The shape can not be finished properly as well. The workaround using Enter/Return does not work in here. Maybe a problem, that lies way more down in some library?

**Comment by Rastopapola** [comment]
Works like a charm now!
